function main_html(){//İlk Acıldıgında Gözüken HTML DİZİSİ.
    if(screen.orientation.type == 'landscape-primary'){
        document.getElementById("table2").innerHTML = "<div class='container'><div class='row'><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style='font-weight:bold;width:100%;height:50vh;background-position-y: 12vw;' id='myChart'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_2'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_3'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_4'></canvas></div></div></div>"; 
           }else if(screen.orientation.type == 'portrait-primary'){
             document.getElementById("table2").innerHTML = "<div class='container'><div class='row'><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style='font-weight:bold;width:100%;height:50vh;' id='myChart'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_2'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_3'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_4'></canvas></div></div></div>";
           }
}
function landscape_html(){//YATAY ÇEVRİLDİĞİNDE GÖZÜKEN KISIM.
    document.getElementById("table2").innerHTML = "<div class='container'><div class='row'><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style='font-weight:bold;width:100%;height:50vh;background-position-y: 12vw;' id='myChart'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_2'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_3'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;background-position-y: 12vw;' id='myChart_4'></canvas></div></div></div>"; 
    
}

function portrait_html(){//DÜZ ÇEVRİLDİĞİNDE GÖZÜKEN KISIM.
    document.getElementById("table2").innerHTML = "<div class='container'><div class='row'><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas style='font-weight:bold;width:100%;height:50vh;' id='myChart'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_2'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_3'></canvas></div><div style ='margin:auto;text-align:center;font-weight:bold;' class='col-md-6'><canvas  style ='width:100%;height:50vh;' id='myChart_4'></canvas></div></div></div>";
}
export {main_html,landscape_html,portrait_html};